config/routes.rb
Vespa::Application.routes.draw do 
  get "profiles/show/:id" => 'profiles#show'
  devise_for :users
  resources :events 
  resources :summoners
  resources :announcements
  get 'streams'  => 'streams#index'
  get 'sponsors' => 'pages#sponsors'
  get 'gallery' => 'pages#gallery'
  root 'pages#home'
end

app/models/summoner.rb
class Summoner < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :summonerLevel, :numericality => { :only_integer => true, :greater_than => 0, :less_than_or_equal_to => 30 }
  
end

app/controllers/summoners_controller.rb
class SummonersController < ApplicationController
  # include Riot::Performer
  before_action :set_summoner, only: [:show, :edit, :update, :destroy]

  # GET /summoners
  # GET /summoners.json
  def index
    @summoners = Summoner.all
  end

  # GET /summoners/1
  # GET /summoners/1.json
  def show
  end

  # GET /summoners/new
  def new
    
    @summoner = Summoner.new
  end

  # GET /summoners/1/edit
  def edit
  end

  # POST /summoners
  # POST /summoners.json
  def create
    @summoner = Summoner.find_by(name: summoner_params[:name])
    @summoner ||= Summoner.new(get_summoner_by_name(summoner_params[:name]))
    current_user.summoners << @summoner
    respond_to do |format|
      if @summoner.save
        format.js
      else
        format.js { } 
      end
    end
  end

  # PATCH/PUT /summoners/1
  # PATCH/PUT /summoners/1.json
  def update
    respond_to do |format|
      if @summoner.update(summoner_params)
        format.html { redirect_to @summoner, notice: 'Summoner was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @summoner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summoners/1
  # DELETE /summoners/1.json
  def destroy
    @summoner.destroy
    respond_to do |format|
      format.html { redirect_to summoners_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_summoner
      @summoner = Summoner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summoner_params
      params.permit(:name)
    end
end

app/views/summoners/_form.html.erb
<%= form_for @summoner, :html => {:class => 'form-horizontal'} do |f| %>
  <% if @summoner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@summoner.errors.count, "error") %> prohibited this summoner from being saved:</h2>

      <ul>
      <% @summoner.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   
  <label for="summoner-name" class="col-sm-2 control-label">Summoner Name</label>

  <div class="form-group col-md-10">
    <%= f.text_field :name, class: "form-control", placeholder: "Enter Summoner Name" %> 
  </div>
  

  <div class="actions">
    <%= f.submit :submit, class: "btn btn-default col-md-offset-2" %>
  </div>
<% end %>

app/views/summoners/create.js.erb
$('#account-list').append('<div class="form-group"><p class="form-control-static"><%= @summoner.name %></p>');
$('#name').val('');

app/views/summoners/edit.html.erb
<h1>Editing summoner</h1>

<%= render 'form' %>

<%= link_to 'Show', @summoner %> |
<%= link_to 'Back', summoners_path %>

app/views/summoners/index.html.erb
<h1>Listing summoners</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @summoners.each do |summoner| %>
      <tr>
        <td><%= link_to 'Show', summoner %></td>
        <td><%= link_to 'Edit', edit_summoner_path(summoner) %></td>
        <td><%= link_to 'Destroy', summoner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Summoner', new_summoner_path %>

app/views/summoners/new.html.erb
<h1>New summoner</h1>

<%= render 'form' %>

<%= link_to 'Back', summoners_path %>

app/views/summoners/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_summoner_path(@summoner) %> |
<%= link_to 'Back', summoners_path %>