config/routes.rb
Vespa::Application.routes.draw do 
  get "profiles/show/:id" => 'profiles#show'
  devise_for :users
  resources :events 
  resources :summoners
  resources :announcements
  get 'streams'  => 'streams#index'
  get 'sponsors' => 'pages#sponsors'
  get 'gallery' => 'pages#gallery'
  root 'pages#home'
end

app/views/pages/about_us.html.erb
<p>We are Virginia's Premiere Organization devoted to bringing eSports to friendly and competitive environments throughout Virginia.</p>

app/views/pages/gallery.html.erb
<div class="container">
<div style='position: relative; padding-bottom: 76%; height: 0; overflow: hidden;'><iframe id='iframe' src='http://flickrit.com/slideshowholder.php?height=75&size=big&userId=129660780@N03&thumbnails=0&transition=0&layoutType=responsive&sort=0' scrolling='no' frameborder='0'style='width:100%; height:100%; position: absolute; top:0; left:0;' ></iframe></div>
</div>

app/views/pages/home.html.erb
<div class="container">
    <%= image_tag("vespa-banner.png", class: 'img-responsive text-center img-rounded') %>
</div>
<hr>
<div class="container">
  <div class="row fill-height">
		<div class="col-md-6">
			<h2>Announcements</h3>
			<hr>
				<% @recent_announcements.each do |announcement| %>
				<div class='announcement'>
						<p>
							<strong> <%= link_to announcement.title, announcement_path(announcement) %> </strong>
							by <i><%= announcement.user %> </i>
						</p>

						<p> <%= simple_format announcement.preview %> </p> 
				</div>
				<% end %>
				<p class="text-center"><%= link_to "View All", announcements_path %></p>
		</div>
    <div class="col-md-6">
      <h2>Upcoming Events</h2>
      <hr>
      <% if @upcoming_events.empty? %>
          <p>No events this week: Check our our calendar for a full schedule</p>
      <% end %>
      <% @upcoming_events.each do |event| %>
          <p>
            <strong> <%= link_to event.title, event_path(event) %></strong>
            <i><%= event.date.to_formatted_s(:long_ordinal) %></i>
          </p>

          <p><%= truncate(event.info, length: 200) %></p>
          <hr>
      <% end %>
      <p class="text-center"><%= link_to "View All", events_path %></p>
      <hr>
    </div>

  </div>
</div>

app/views/pages/index.html.erb
<hr>
<div class="jumbotron">
  <div class="container">
    <div class="row"><p>

      <div class="col-md-4">
        <h1 class="text-center">VeSPA</h1>

        <h3 class="text-center">Virgina eSports Association</h3>

        <p class="text-center">We are Virginia's Premiere Organization devoted to bringing eSports to friendly and
          competitive environments throughout Virginia.</p>
      </div>
      <div class="col-md-8">
        <%= image_tag("vespa-banner.png", class: 'img-responsive text-center') %>
      </div>
    </div>
    <p>
  </div>
</div>
<hr>
<div class="container">
  <div class="row fill-height">
    <div class="col-md-6">
      <h2>Announcements</h2>
      <hr>
      <% @recent_announcements.each do |announcement| %>
          <p>
            <strong> <%= link_to announcement.title, announcement_path(announcement) %> </strong>
            by <i><%= announcement.user %> </i>
          </p>

          <p> <%= simple_format announcement.preview %> </p> <%= link_to "(read more)", announcement_path(announcement) %>
          <hr>
      <% end %>
      <p class="text-center"><%= link_to "View All", announcements_path %></p>
      <hr>
    </div>
    <div class="col-md-6">
      <h2>Upcoming Events</h2>
      <hr>
      <% if @upcoming_events.empty? %>
          <p>No events this week: Check our our calendar for a full schedule</p>
      <% end %>
      <% @upcoming_events.each do |event| %>
          <p>
            <strong> <%= link_to event.title, event_path(event) %></strong>
            <i><%= event.date.to_formatted_s(:long_ordinal) %></i>
          </p>

          <p><%= truncate(event.info, length: 200) %></p>
          <hr>
      <% end %>
      <p class="text-center"><%= link_to "View All", events_path %></p>
      <hr>
    </div>

  </div>
</div>

app/views/pages/sponsors.html.erb
<h1>SPONSORS</h1>