config/routes.rb
Vespa::Application.routes.draw do 
  get "profiles/show/:id" => 'profiles#show'
  devise_for :users
  resources :events 
  resources :summoners
  resources :announcements
  get 'streams'  => 'streams#index'
  get 'sponsors' => 'pages#sponsors'
  get 'gallery' => 'pages#gallery'
  root 'pages#home'
end

app/views/layouts/_footer.html.erb
<footer class="footer" background-color"#cccccc">
	<div class="container">
		<%= image_tag("gameskinny.png", class: 'col-md-4')%>
		<%= image_tag("guildlaunch.png", class: 'col-md-4')%>
		<%= image_tag("blacksburg-eye.png", class: 'col-md-4')%>
  </div>

	<div class="container">
		<%= link_to image_tag("facebook.png"), "https://www.facebook.com/groups/VirginiaeSportsAssociation/" %>
		<%= link_to image_tag("twitter.png"), "https://twitter.com/VeSPALive" %>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "News", announcements_path %></li>
        <li><%= link_to "Events", events_path %></li>
        <li><%= link_to "Stream", streams_path %></li>
        <li><%= link_to "Photos", gallery_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
            <a href='<%= "/profiles/show/#{current_user.id}" %>' >
              <%= image_tag current_user.gravatar_url, class: 'img-rounded', size: '20x20' %>
              <%= current_user.email %> 
            </a>
          </li>
          <% if current_user.is_admin? %>
            <li class="dropdown">
              <a href="#" class="dropdown" data-toggle="dropdown"><span class="glyphicon glyphicon-edit"></span> <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li>
                  <%= link_to new_announcement_path do %>
                    <span class='glyphicon glyphicon-pencil'></span> New Post</a>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_event_path do %>
                    <span class='glyphicon glyphicon-calendar'></span> New Event</a>
                  <% end %>
                </li>
              </ul>
            </li>
          <% end %>
          <li>
            <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-cog"></span>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, :method => :delete  do %>
              <span class='glyphicon glyphicon-off'></span>
            <% end %>
          </li>
        <% else %>
          <%= form_for("user", :url => user_session_path, :html => {class: "navbar-form navbar-right", role: "form"}) do |f| %>
            <div class="form-group"><%= f.text_field :email, class: "form-control", placeholder: "Email" %></div>
            <div class="form-group"><%= f.password_field :password, class: "form-control", placeholder: "Password" %></div>
            <div class="form-group"><%= f.submit 'Sign In', class: "btn btn-success" %></div>
            <div class="form-group"><%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %></div>
          <% end %>
        <% end %>
      </ul>
      <!--/.navbar-collapse -->
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Virginia eSports Association</title>
		<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
		<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/navbar" %>
		<%= bootstrap_flash %>
		<div class="container main-content">
			<%= yield %>
			<hr>
		</div>
			<%= render "layouts/footer" %>
	</body>
</html>